export default function needsWebSearch(content: string): boolean {
  const tlds = [
    "com",
    "net",
    "org",
    "info",
    "xyz",
    "dev",
    "app",
    "co",
    "io",
    "store",
    "site",
    "online",
    "shop",
    "blog",
    "live",
    "tv",
    "news",
    "media",
    "tech",
    "ai",
    "me",
  ]
  const domainPattern = new RegExp(
    `\\b(?:https?:\\/\\/)?(?:www\\.)?[\\w-]+\\.(${tlds.join("|")})\\b`,
    "i",
  )
  const searchKeywords = {
    // English
    en: [
      "web",
      "www",
      "search",
      "latest",
      "recent",
      "current",
      "today",
      "now",
      "this week",
      "this month",
      "this year",
      "news",
      "breaking",
      "what is happening",
      "what's happening",
      "updates",
      "price of",
      "stock price",
      "market",
      "trading",
      "cryptocurrency",
      "bitcoin",
      "ethereum",
      "weather",
      "temperature",
      "forecast",
      "climate",
      "when did",
      "when was",
      "when will",
      "what time",
      "schedule",
      "who is",
      "who was",
      "who are",
      "biography",
      "what happened",
      "what's new",
      "events",
      "incident",
      "how much",
      "cost",
      "expensive",
      "cheap",
      "budget",
      "where is",
      "location",
      "address",
      "directions",
      "reviews",
      "rating",
      "opinion",
      "feedback",
      "compare",
      "vs",
      "versus",
      "difference",
      "better",
      "release date",
      "launch",
      "announcement",
      "availability",
      "statistics",
      "data",
      "numbers",
      "percentage",
      "growth",
      "trending",
      "popular",
      "viral",
      "famous",
      "live",
      "streaming",
      "broadcast",
      "real-time",
    ],

    // Spanish
    es: [
      "buscar",
      "último",
      "últimos",
      "reciente",
      "actual",
      "hoy",
      "ahora",
      "esta semana",
      "este mes",
      "este año",
      "noticias",
      "qué está pasando",
      "qué pasa",
      "actualizaciones",
      "precio de",
      "precio",
      "mercado",
      "comercio",
      "criptomoneda",
      "clima",
      "tiempo",
      "temperatura",
      "pronóstico",
      "cuándo",
      "cuándo fue",
      "cuándo será",
      "horario",
      "quién es",
      "quién fue",
      "biografía",
      "qué pasó",
      "qué hay de nuevo",
      "eventos",
      "incidente",
      "cuánto cuesta",
      "costo",
      "caro",
      "barato",
      "dónde está",
      "ubicación",
      "dirección",
      "reseñas",
      "calificación",
      "opinión",
      "comparar",
      "diferencia",
      "mejor",
      "fecha de lanzamiento",
      "anuncio",
      "disponibilidad",
      "estadísticas",
      "datos",
      "números",
      "crecimiento",
      "tendencia",
      "popular",
      "viral",
      "famoso",
      "en vivo",
      "transmisión",
      "tiempo real",
    ],

    // French
    fr: [
      "rechercher",
      "dernier",
      "récent",
      "actuel",
      "aujourd'hui",
      "maintenant",
      "cette semaine",
      "ce mois",
      "cette année",
      "nouvelles",
      "actualités",
      "que se passe-t-il",
      "mises à jour",
      "prix de",
      "prix",
      "marché",
      "commerce",
      "cryptomonnaie",
      "météo",
      "temps",
      "température",
      "prévisions",
      "quand",
      "quand est-ce que",
      "horaire",
      "qui est",
      "qui était",
      "biographie",
      "que s'est-il passé",
      "quoi de neuf",
      "événements",
      "incident",
      "combien coûte",
      "coût",
      "cher",
      "pas cher",
      "où est",
      "emplacement",
      "adresse",
      "avis",
      "note",
      "opinion",
      "comparer",
      "différence",
      "meilleur",
      "date de sortie",
      "annonce",
      "disponibilité",
      "statistiques",
      "données",
      "chiffres",
      "croissance",
      "tendance",
      "populaire",
      "viral",
      "célèbre",
      "en direct",
      "diffusion",
      "temps réel",
    ],

    // German
    de: [
      "suchen",
      "neueste",
      "aktuell",
      "heute",
      "jetzt",
      "diese woche",
      "diesen monat",
      "dieses jahr",
      "nachrichten",
      "was passiert",
      "updates",
      "preis von",
      "preis",
      "markt",
      "handel",
      "kryptowährung",
      "wetter",
      "temperatur",
      "vorhersage",
      "wann",
      "wann war",
      "wann wird",
      "zeitplan",
      "wer ist",
      "wer war",
      "biografie",
      "was ist passiert",
      "was gibt es neues",
      "ereignisse",
      "vorfall",
      "wie viel kostet",
      "kosten",
      "teuer",
      "billig",
      "wo ist",
      "standort",
      "adresse",
      "bewertungen",
      "bewertung",
      "meinung",
      "vergleichen",
      "unterschied",
      "besser",
      "veröffentlichungsdatum",
      "ankündigung",
      "verfügbarkeit",
      "statistiken",
      "daten",
      "zahlen",
      "wachstum",
      "trend",
      "beliebt",
      "viral",
      "berühmt",
      "live",
      "übertragung",
      "echtzeit",
    ],

    // Italian
    it: [
      "ricerca",
      "ultimo",
      "recente",
      "attuale",
      "oggi",
      "ora",
      "questa settimana",
      "questo mese",
      "quest'anno",
      "notizie",
      "cosa sta succedendo",
      "aggiornamenti",
      "prezzo di",
      "prezzo",
      "mercato",
      "commercio",
      "criptovaluta",
      "tempo",
      "temperatura",
      "previsioni",
      "quando",
      "quando è stato",
      "quando sarà",
      "orario",
      "chi è",
      "chi era",
      "biografia",
      "cosa è successo",
      "cosa c'è di nuovo",
      "eventi",
      "incidente",
      "quanto costa",
      "costo",
      "caro",
      "economico",
      "dove si trova",
      "posizione",
      "indirizzo",
      "recensioni",
      "valutazione",
      "opinione",
      "confrontare",
      "differenza",
      "migliore",
      "data di rilascio",
      "annuncio",
      "disponibilità",
      "statistiche",
      "dati",
      "numeri",
      "crescita",
      "tendenza",
      "popolare",
      "virale",
      "famoso",
      "dal vivo",
      "trasmissione",
      "tempo reale",
    ],

    // Portuguese
    pt: [
      "buscar",
      "último",
      "recente",
      "atual",
      "hoje",
      "agora",
      "esta semana",
      "este mês",
      "este ano",
      "notícias",
      "o que está acontecendo",
      "atualizações",
      "preço de",
      "preço",
      "mercado",
      "comércio",
      "criptomoeda",
      "clima",
      "tempo",
      "temperatura",
      "previsão",
      "quando",
      "quando foi",
      "quando será",
      "horário",
      "quem é",
      "quem foi",
      "biografia",
      "o que aconteceu",
      "o que há de novo",
      "eventos",
      "incidente",
      "quanto custa",
      "custo",
      "caro",
      "barato",
      "onde fica",
      "localização",
      "endereço",
      "avaliações",
      "classificação",
      "opinião",
      "comparar",
      "diferença",
      "melhor",
      "data de lançamento",
      "anúncio",
      "disponibilidade",
      "estatísticas",
      "dados",
      "números",
      "crescimento",
      "tendência",
      "popular",
      "viral",
      "famoso",
      "ao vivo",
      "transmissão",
      "tempo real",
    ],

    // Japanese
    ja: [
      "検索",
      "最新",
      "最近",
      "現在",
      "今日",
      "今",
      "今週",
      "今月",
      "今年",
      "ニュース",
      "何が起こっている",
      "更新",
      "価格",
      "株価",
      "市場",
      "取引",
      "暗号通貨",
      "天気",
      "気温",
      "予報",
      "いつ",
      "いつだった",
      "スケジュール",
      "誰",
      "誰だった",
      "伝記",
      "何が起こった",
      "新しいこと",
      "イベント",
      "事件",
      "いくら",
      "費用",
      "高い",
      "安い",
      "どこ",
      "場所",
      "住所",
      "レビュー",
      "評価",
      "意見",
      "比較",
      "違い",
      "より良い",
      "発売日",
      "発表",
      "利用可能",
      "統計",
      "データ",
      "数字",
      "成長",
      "トレンド",
      "人気",
      "バイラル",
      "有名",
      "ライブ",
      "配信",
      "リアルタイム",
    ],

    // Korean
    ko: [
      "검색",
      "최신",
      "최근",
      "현재",
      "오늘",
      "지금",
      "이번 주",
      "이번 달",
      "올해",
      "뉴스",
      "무슨 일이 일어나고 있는지",
      "업데이트",
      "가격",
      "주가",
      "시장",
      "거래",
      "암호화폐",
      "날씨",
      "온도",
      "예보",
      "언제",
      "언제였는지",
      "일정",
      "누구",
      "누구였는지",
      "전기",
      "무슨 일이 일어났는지",
      "새로운 것",
      "이벤트",
      "사건",
      "얼마",
      "비용",
      "비싼",
      "싼",
      "어디",
      "위치",
      "주소",
      "리뷰",
      "평가",
      "의견",
      "비교",
      "차이",
      "더 나은",
      "출시일",
      "발표",
      "이용 가능",
      "통계",
      "데이터",
      "숫자",
      "성장",
      "트렌드",
      "인기",
      "바이럴",
      "유명한",
      "라이브",
      "스트리밍",
      "실시간",
    ],

    // Chinese
    zh: [
      "搜索",
      "最新",
      "最近",
      "当前",
      "今天",
      "现在",
      "本周",
      "本月",
      "今年",
      "新闻",
      "发生什么",
      "更新",
      "价格",
      "股价",
      "市场",
      "交易",
      "加密货币",
      "天气",
      "温度",
      "预报",
      "什么时候",
      "什么时候是",
      "时间表",
      "谁",
      "谁是",
      "传记",
      "发生了什么",
      "有什么新的",
      "事件",
      "事故",
      "多少钱",
      "成本",
      "昂贵",
      "便宜",
      "在哪里",
      "位置",
      "地址",
      "评论",
      "评级",
      "意见",
      "比较",
      "差异",
      "更好",
      "发布日期",
      "公告",
      "可用性",
      "统计",
      "数据",
      "数字",
      "增长",
      "趋势",
      "流行",
      "病毒式",
      "著名",
      "直播",
      "流媒体",
      "实时",
    ],
  }

  const lowerContent = content.toLowerCase()
  const domainMatch = domainPattern.test(lowerContent)
  if (domainMatch) return true

  const keywordMatch = Object.values(searchKeywords).some((keywords) =>
    keywords.some((keyword) => lowerContent.includes(keyword.toLowerCase())),
  )

  return keywordMatch
}
