# GitHub Secret Scanning Configuration
# This file tells GitHub's secret scanning to ignore certain patterns

# Firebase API keys in GoogleService-Info.plist are meant to be public
# They are embedded in iOS apps and protected by Firebase App Check and bundle ID restrictions
apps/mobile/ios/App/App/GoogleService-Info.plist:*

# Firebase configuration files for Android (if added in the future)
# These are also meant to be public and embedded in Android apps
apps/mobile/android/app/google-services.json:*
