steps:
  - label: "🔧 Setup & Install"
    key: "setup"
    command: |
      echo "--- Installing pnpm globally"
      npm install -g pnpm@9.1.2
      echo "--- Verifying pnpm"
      pnpm --version
      which pnpm
      echo "--- Installing dependencies"
      pnpm install --frozen-lockfile
      echo "--- Verifying turbo"
      pnpm exec turbo --version
    agents:
      queue: "default"

  - wait

  - label: "🏗️ Build Packages"
    key: "build-packages"
    command: |
      echo "--- Ensuring pnpm"
      npm install -g pnpm@9.1.2
      echo "--- Installing dependencies"
      pnpm install --frozen-lockfile
      echo "--- Building @chrryai packages"
      pnpm exec turbo build --filter=@chrryai/chrry --filter=@chrryai/waffles --filter=@chrryai/pepper
    depends_on: "setup"
    agents:
      queue: "default"

  - wait

  - label: "🏗️ Build Apps"
    key: "build-apps"
    command: |
      echo "--- Ensuring pnpm"
      npm install -g pnpm@9.1.2
      echo "--- Installing dependencies"
      pnpm install --frozen-lockfile
      echo "--- Building Next.js apps"
      pnpm exec turbo build --filter=chrrydotdev --filter=web
    depends_on: "build-packages"
    agents:
      queue: "default"
    env:
      NODE_OPTIONS: "--max-old-space-size=4096"
      # Next.js build env vars (from Buildkite secrets)
      NEXTAUTH_URL: "${NEXTAUTH_URL}"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
      DATABASE_URL: "${DATABASE_URL}"
      UPLOADTHING_SECRET: "${UPLOADTHING_SECRET}"
      UPLOADTHING_APP_ID: "${UPLOADTHING_APP_ID}"
      DEEPSEEK_API_KEY: "${DEEPSEEK_API_KEY}"
      CHATGPT_API_KEY: "${CHATGPT_API_KEY}"
      STRIPE_SECRET_KEY: "${STRIPE_SECRET_KEY}"
      STRIPE_WEBHOOK_SECRET: "${STRIPE_WEBHOOK_SECRET}"

  - label: "🧪 Lint"
    key: "lint"
    command: |
      echo "--- Ensuring pnpm"
      npm install -g pnpm@9.1.2
      echo "--- Installing dependencies"
      pnpm install --frozen-lockfile --no-optional
      echo "--- Verifying eslint dependencies"
      ls -la node_modules/@typescript-eslint/ || echo "Missing typescript-eslint"
      echo "--- Running linters"
      pnpm exec turbo lint
    depends_on: "setup"
    agents:
      queue: "default"

agents:
  queue: "default"

env:
  CI: "true"
  NODE_ENV: "production"
  TURBO_TELEMETRY_DISABLED: "1"
