services:
  minio:
    image: ghcr.io/coollabsio/minio:RELEASE.2025-10-15T17-29-55Z
    # Console only accessible via localhost for security
    command: server /data --console-address "127.0.0.1:9001"
    environment:
      - MINIO_SERVER_URL=$MINIO_SERVER_URL
      - MINIO_ROOT_USER=$SERVICE_USER_MINIO
      - MINIO_ROOT_PASSWORD=$SERVICE_PASSWORD_MINIO
      # MINIO_BROWSER=off removed - console available on localhost only
    ports:
      - 127.0.0.1:9001:9001 # Bind to localhost only
    volumes:
      - minio-data:/data
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      interval: 5s
      timeout: 20s
      retries: 10
