/**
 * UI Components Barrel Export
 *
 * This file exports all components from their individual directories.
 * Maintains backward compatibility with existing imports.
 *
 * Usage:
 *   import { Button, Modal, Chat } from 'chrry'
 *
 * Auto-generated by migrate-components.js
 */

// Re-export commonly used utilities and hooks
export * from "./hooks"
export * from "./lib"
export * from "./utils"
export * from "./schemas"

// Re-export UI components
export { default as Sidebar } from "./Sidebar"
export { default as Chrry } from "./Chrry"
export { default as Store } from "./Store"
export { HistoryRouterProvider } from "./context/providers/HistoryRouterProvider"

// Make Chrry the default export
export { default } from "./Chrry"
