import { drizzleZeroConfig } from "drizzle-zero"
// Import your existing Drizzle schema
import * as schema from "@repo/db/src/schema"
// drizzle-zero.config.ts

export default drizzleZeroConfig(schema, {
  tables: {
    // Core tables
    users: {
      id: true,
      email: true,
      name: true,
      userName: true,
      image: true,
      role: true,
      credits: true,
      emailVerified: true,
      appleId: true,
      fingerprint: true,
      apiKey: true,
      password: true,
      suggestions: true,
      characterProfilesEnabled: true,
      migratedFromGuest: true,
      createdOn: true,
      updatedOn: true,
    },
    guests: {
      id: true,
      fingerprint: true,
      ip: true,
      isBot: true,
      email: true,
      credits: true,
      country: true,
      city: true,
      weather: true,
      timezone: true,
      suggestions: true,
      migratedToUser: true,
      activeOn: true,
      createdOn: true,
      updatedOn: true,
    },
    accounts: {
      id: true,
      userId: true,
      type: true,
      provider: true,
      providerAccountId: true,
      refresh_token: true,
      access_token: true,
      expires_at: true,
      token_type: true,
      scope: true,
      id_token: true,
      session_state: true,
    },
    threads: {
      id: true,
      userId: true,
      guestId: true,
      title: true,
      visibility: true,
      isIncognito: true,
      isMainThread: true,
      star: true,
      bookmarks: true,
      appId: true,
      taskId: true,
      createdOn: true,
      updatedOn: true,
    },
    messages: {
      id: true,
      userId: true,
      guestId: true,
      threadId: true,
      agentId: true,
      content: true,
      message: true,
      files: true,
      images: true,
      video: true,
      audio: true,
      reactions: true,
      actions: true,
      creditCost: true,
      readOn: true,
      clientId: true,
      moodId: true,
      createdOn: true,
      updatedOn: true,
    },
    aiAgents: {
      id: true,
      name: true,
      state: true,
      userId: true,
      guestId: true,
      appId: true,
      creditCost: true,
      order: true,
      model: true,
      systemPrompt: true,
      temperature: true,
      maxTokens: true,
      tools: true,
    },
    apps: {
      id: true,
      name: true,
      slug: true,
      title: true,
      description: true,
      icon: true,
      themeColor: true,
      backgroundColor: true,
      visibility: true,
      userId: true,
      guestId: true,
      storeId: true,
      defaultModel: true,
      capabilities: true,
      tools: true,
      highlights: true,
      images: true,
      features: true,
      tips: true,
      tipsTitle: true,
      onlyAgent: true,
      extend: true,
      pricing: true,
      tier: true,
      placeholder: true,
      installCount: true,
      createdOn: true,
      updatedOn: true,
    },
    stores: {
      id: true,
      name: true,
      slug: true,
      domain: true,
      visibility: true,
      userId: true,
      guestId: true,
      teamId: true,
      appId: true,
      parentStoreId: true,
      createdOn: true,
      updatedOn: true,
    },
    memories: {
      id: true,
      userId: true,
      guestId: true,
      appId: true,
      content: true,
      title: true,
      tags: true,
      category: true,
      importance: true,
      usageCount: true,
      lastUsedAt: true,
      embedding: true,
      sourceThreadId: true,
      sourceMessageId: true,
      metadata: true,
      createdOn: true,
      updatedOn: true,
    },
    characterProfiles: {
      id: true,
      userId: true,
      guestId: true,
      threadId: true,
      agentId: true,
      name: true,
      tags: true,
      visibility: true,
      pinned: true,
      createdOn: true,
      updatedOn: true,
    },
    tasks: {
      id: true,
      userId: true,
      guestId: true,
      title: true,
      description: true,
      status: true,
      priority: true,
      dueDate: true,
      order: true,
      createdOn: true,
      updatedOn: true,
    },
    moods: {
      id: true,
      userId: true,
      guestId: true,
      taskId: true,
      mood: true,
      energy: true,
      note: true,
      createdOn: true,
      updatedOn: true,
    },
    expenses: {
      id: true,
      userId: true,
      guestId: true,
      threadId: true,
      amount: true,
      currency: true,
      category: true,
      description: true,
      date: true,
      createdOn: true,
      updatedOn: true,
    },
    budgets: {
      id: true,
      userId: true,
      guestId: true,
      category: true,
      amount: true,
      period: true,
      isActive: true,
      createdOn: true,
      updatedOn: true,
    },
    subscriptions: {
      id: true,
      userId: true,
      guestId: true,
      plan: true,
      status: true,
      provider: true,
      subscriptionId: true,
      sessionId: true,
      currentPeriodEnd: true,
      cancelAtPeriodEnd: true,
      createdOn: true,
      updatedOn: true,
    },
    creditUsage: {
      id: true,
      userId: true,
      guestId: true,
      agentId: true,
      creditCost: true,
      messageType: true,
      threadId: true,
      messageId: true,
      appId: true,
      createdOn: true,
    },
    collaborations: {
      id: true,
      threadId: true,
      userId: true,
      status: true,
      role: true,
      createdOn: true,
      updatedOn: true,
    },
    instructions: {
      id: true,
      userId: true,
      guestId: true,
      appId: true,
      content: true,
      createdOn: true,
      updatedOn: true,
    },
    placeHolders: {
      id: true,
      userId: true,
      guestId: true,
      threadId: true,
      appId: true,
      text: true,
      createdOn: true,
      updatedOn: true,
    },
    calendarEvents: {
      id: true,
      userId: true,
      guestId: true,
      title: true,
      description: true,
      startTime: true,
      endTime: true,
      location: true,
      attendees: true,
      googleEventId: true,
      createdOn: true,
      updatedOn: true,
    },
    installs: {
      id: true,
      appId: true,
      userId: true,
      guestId: true,
      order: true,
      isPinned: true,
      installedAt: true,
      uninstalledAt: true,
    },
    storeInstalls: {
      id: true,
      storeId: true,
      appId: true,
      displayOrder: true,
      installedAt: true,
      updatedOn: true,
    },
    // appOrders: Composite key table - skip for now
    // appOrders: {
    //   appId: true,
    //   storeId: true,
    //   userId: true,
    //   guestId: true,
    //   order: true,
    //   createdOn: true,
    //   updatedOn: true,
    // },
    // appExtend: Composite key table - skip for now
    // appExtend: {
    //   appId: true,
    //   toId: true,
    // },
    devices: {
      id: true,
      userId: true,
      guestId: true,
      fingerprint: true,
      userAgent: true,
      platform: true,
      createdOn: true,
      updatedOn: true,
    },
    timers: {
      id: true,
      userId: true,
      guestId: true,
      fingerprint: true,
      startTime: true,
      endTime: true,
      duration: true,
      isRunning: true,
      createdOn: true,
      updatedOn: true,
    },
    teams: {
      id: true,
      name: true,
      slug: true,
      createdOn: true,
      updatedOn: true,
    },
  },
  // Many-to-many relationships
  // manyToMany: {
  //   threads: {
  //     collaborators: ["collaborations", "users"],
  //   },
  //   apps: {
  //     extends: ["appExtend", "apps"],
  //   },
  // },
})
