name: Sync Vex to Separate Repo

on:
  workflow_dispatch: # Manual trigger
  push:
    branches:
      - chrry # Only trigger when pushing to chrry branch

jobs:
  sync-vex:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Vex repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history
          token: ${{ secrets.CHRRY_SYNC_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for sensitive data
        run: |
          echo "🔒 Running security checks..."

          # Check for .env files
          if git ls-files | grep -E "\.env$|\.env\.local$|\.env\.production\.local$"; then
            echo "❌ ERROR: .env files found in git!"
            exit 1
          fi

          # Check for API keys (basic check)
          if git grep -E "sk-[A-Za-z0-9]{48}|AKIA[A-Z0-9]{16}" -- '*.ts' '*.tsx' '*.js' '*.json' ':!node_modules'; then
            echo "❌ ERROR: Potential API keys found in code!"
            exit 1
          fi

          echo "✅ Security checks passed"

      - name: Create fresh Vex commit
        run: |
          # Create temporary directory for Vex
          mkdir -p /tmp/vex-fresh

          # Copy entire repo except sensitive files
          rsync -av --exclude='.git' --exclude='node_modules' --exclude='.env*' . /tmp/vex-fresh/

          # Initialize fresh repo
          cd /tmp/vex-fresh
          git init

          # Configure Git for this repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Remove ALL workflow files to avoid permission issues
          # GitHub requires 'workflow' scope on PAT to modify .github/workflows/
          rm -rf .github/workflows/

          git add .

          # Create single clean commit with current state
          COMMIT_MSG="Update Vex Platform 🚀

          Synced from private monorepo
          Latest changes from all packages"

          git commit -m "$COMMIT_MSG"

      - name: Push to Vex repo
        run: |
          cd /tmp/vex-fresh

          # Add Vex remote
          git remote add origin https://x-access-token:${{ secrets.CHRRY_SYNC_TOKEN }}@github.com/chrryAI/vex.git

          # Create main branch and force push (clean history)
          git branch -M main
          git push -f origin main
